import numpy as np
from PySide2.QtCore import QObject, Signal, Slot, QTimer
from .common import RawData, POINTS


class ExperimentSignals(QObject):
    """Signals that may be generated by the experiment worker.

    new_data : RawData
        Contains the parallel, perpendicular, reference, and shutter traces
        from the oscilloscope. Generated for each acquisition.
    """

    new_data = Signal(RawData)


class ExperimentWorker(QObject):
    """Worker thread responsible for controlling data acquisition.

    This worker thread communicates with the oscilloscope, setting triggers and
    transfering data when it's ready.

    Notes
    -----
    Currently this only generates dummy data and does not communicate with the
    oscilloscope.
    """

    def __init__(self):
        super(ExperimentWorker, self).__init__()
        self.signals = ExperimentSignals()
        self.rng = np.random.default_rng()
        self.timer = QTimer()
        self.timer.setInterval(10)  # in ms
        self.timer.timeout.connect(self.generate)
        self.timer.start()

    @Slot()
    def generate(self):
        """A temporary method that generates dummy data on each iteration of the timer.
        """
        par = self.rng.random(POINTS)
        perp = self.rng.random(POINTS)
        ref = self.rng.random(POINTS)
        shutter = self.rng.random(POINTS)
        data = RawData(par, perp, ref, shutter)
        self.signals.new_data.emit(data)

    def finish(self):
        """A temporary method to stop the timer.
        """
        self.timer.stop()
